#!/bin/sh

OBJOUT=0

for i in $@; do
	if [ $i == "-O" ];then
		OBJOUT=1
	fi
	if [ $i == binary -a $OBJOUT == 1 ];then
		RMSTACK="-R.stack"
	fi
	if [ $i == "-Obinary" ];then
		RMSTACK="-R.stack"
	fi
done

${KOS_OBJCOPY} $RMSTACK $@
