# KallistiOS ##version##
#
# examples/dreamcast/sound/cdda/Makefile
# (c)2002 Dan Potter
#

all:
	$(KOS_MAKE) -C basic_cdda

clean:
	$(KOS_MAKE) -C basic_cdda clean
		
dist:
	$(KOS_MAKE) -C basic_cdda dist


