# KallistiOS ##version##
#
# examples/dreamcast/pvr/Makefile
# (c)2002 Dan Potter
#

all:
	$(KOS_MAKE) -C plasma
	$(KOS_MAKE) -C pvrmark
	$(KOS_MAKE) -C pvrmark_strips
	$(KOS_MAKE) -C pvrmark_strips_direct
	$(KOS_MAKE) -C texture_render
	$(KOS_MAKE) -C modifier_volume
	$(KOS_MAKE) -C modifier_volume_tex
	$(KOS_MAKE) -C cheap_shadow
	$(KOS_MAKE) -C bumpmap

clean:
	$(KOS_MAKE) -C plasma clean
	$(KOS_MAKE) -C pvrmark clean
	$(KOS_MAKE) -C pvrmark_strips clean
	$(KOS_MAKE) -C pvrmark_strips_direct clean
	$(KOS_MAKE) -C texture_render clean
	$(KOS_MAKE) -C modifier_volume clean
	$(KOS_MAKE) -C modifier_volume_tex clean
	$(KOS_MAKE) -C cheap_shadow clean
	$(KOS_MAKE) -C bumpmap clean

dist:
	$(KOS_MAKE) -C plasma dist
	$(KOS_MAKE) -C pvrmark dist
	$(KOS_MAKE) -C pvrmark_strips dist
	$(KOS_MAKE) -C pvrmark_strips_direct dist
	$(KOS_MAKE) -C texture_render dist
	$(KOS_MAKE) -C modifier_volume dist
	$(KOS_MAKE) -C modifier_volume_tex dist
	$(KOS_MAKE) -C cheap_shadow dist
	$(KOS_MAKE) -C bumpmap dist
