# KallistiOS ##version##
#
# examples/dreamcast/lwip/Makefile
#

all:
	$(KOS_MAKE) -C dns-client
	$(KOS_MAKE) -C httpd
#	$(KOS_MAKE) -C dcload-ip-lwip-test

clean:
	$(KOS_MAKE) -C dns-client clean
	$(KOS_MAKE) -C httpd clean
#	$(KOS_MAKE) -C dcload-ip-lwip-test clean

dist:
	$(KOS_MAKE) -C dns-client dist
	$(KOS_MAKE) -C httpd dist
#	$(KOS_MAKE) -C dcload-ip-lwip-test dist
