# KallistiOS ##version##
#
# examples/dreamcast/cpp/Makefile
# (c)2001-2002 Dan Potter
#

all:
	$(KOS_MAKE) -C gltest
	$(KOS_MAKE) -C dcplib
	$(KOS_MAKE) -C clock
	$(KOS_MAKE) -C modplug_test

clean:
	$(KOS_MAKE) -C gltest clean
	$(KOS_MAKE) -C dcplib clean
	$(KOS_MAKE) -C clock clean
	$(KOS_MAKE) -C modplug_test clean
		
dist:
	$(KOS_MAKE) -C gltest dist
	$(KOS_MAKE) -C dcplib dist
	$(KOS_MAKE) -C clock dist
	$(KOS_MAKE) -C modplug_test dist


