# KallistiOS ##version##
#
# examples/dreamcast/conio/Makefile
# (c)2002 Dan Potter
#

all:
	$(KOS_MAKE) -C basic
	$(KOS_MAKE) -C wump
	$(KOS_MAKE) -C adventure
	$(KOS_MAKE) -C kosh

clean:
	$(KOS_MAKE) -C basic clean
	$(KOS_MAKE) -C wump clean
	$(KOS_MAKE) -C adventure clean
	$(KOS_MAKE) -C kosh clean
		
dist:
	$(KOS_MAKE) -C basic dist
	$(KOS_MAKE) -C wump dist
	$(KOS_MAKE) -C adventure dist
	$(KOS_MAKE) -C kosh dist


