# KallistiOS ##version##
#
# examples/dreamcast/dreameye/Makefile
# Copyright (C) 2009 Lawrence Sebald
#

all:
	$(KOS_MAKE) -C basic
	$(KOS_MAKE) -C sd

clean:
	$(KOS_MAKE) -C basic clean
	$(KOS_MAKE) -C sd clean

dist:
	$(KOS_MAKE) -C basic dist
	$(KOS_MAKE) -C sd dist

