# KallistiOS ##version##
#
# examples/dreamcast/sound/Makefile
# (c)2002 Dan Potter
#

all:
	$(KOS_MAKE) -C ghettoplay-vorbis
	$(KOS_MAKE) -C hello-ogg
	$(KOS_MAKE) -C hello-mp3
	$(KOS_MAKE) -C cdda
	$(KOS_MAKE) -C hello-opus

clean:
	$(KOS_MAKE) -C ghettoplay-vorbis clean
	$(KOS_MAKE) -C hello-ogg clean
	$(KOS_MAKE) -C hello-mp3 clean
	$(KOS_MAKE) -C cdda clean
	$(KOS_MAKE) -C hello-opus clean
		
dist:
	$(KOS_MAKE) -C ghettoplay-vorbis dist
	$(KOS_MAKE) -C hello-ogg dist
	$(KOS_MAKE) -C hello-mp3 dist
	$(KOS_MAKE) -C cdda dist
	$(KOS_MAKE) -C hello-opus dist


