# KallistiOS ##version##
#
# examples/dreamcast/video/Makefile
# Copyright (C) 2002 Dan Potter
#

all:
	$(KOS_MAKE) -C bfont
	$(KOS_MAKE) -C palmenu

clean:
	$(KOS_MAKE) -C bfont clean
	$(KOS_MAKE) -C palmenu clean

dist:
	$(KOS_MAKE) -C bfont dist
	$(KOS_MAKE) -C palmenu dist

