# KallistiOS ##version##
#
# examples/dreamcast/network/Makefile
# (c)2002 Dan Potter
#

all:
	$(KOS_MAKE) -C basic
	$(KOS_MAKE) -C ping
	$(KOS_MAKE) -C ping6
	$(KOS_MAKE) -C udpecho6
	$(KOS_MAKE) -C dns-client

clean:
	$(KOS_MAKE) -C basic clean
	$(KOS_MAKE) -C ping clean
	$(KOS_MAKE) -C ping6 clean
	$(KOS_MAKE) -C udpecho6 clean
	$(KOS_MAKE) -C dns-client clean

dist:
	$(KOS_MAKE) -C basic dist
	$(KOS_MAKE) -C ping dist
	$(KOS_MAKE) -C ping6 dist
	$(KOS_MAKE) -C udpecho6 dist
	$(KOS_MAKE) -C dns-client dist
