# KallistiOS ##version##
#
# examples/dreamcast/tsunami/Makefile
# (c)2002 Dan Potter
#

all:
	$(KOS_MAKE) -C font
	$(KOS_MAKE) -C banner
	$(KOS_MAKE) -C genmenu

clean:
	$(KOS_MAKE) -C font clean
	$(KOS_MAKE) -C banner clean
	$(KOS_MAKE) -C genmenu clean
		
dist:
	$(KOS_MAKE) -C font dist
	$(KOS_MAKE) -C banner dist
	$(KOS_MAKE) -C genmenu dist


